[package]
name = "exploit_shellschock"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
reqwest = { version = "0.12.11" , features = ["blocking"] }
tokio = { version = "1.42.0" , features = ["full"] }
